<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>Mute MIC Uninstaller</AssemblyName>
    <RootNamespace>MuteMIC.Uninstaller</RootNamespace>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>1.0.2</Version>
    <Product>Mute MIC Uninstaller</Product>
  </PropertyGroup>

</Project>
